image: maven:latest

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - mvn compile
    - mvn package

test:
  stage: test
  script:
    - mvn test

deploy:
  stage: deploy
  script:
    - mvn javadoc:javadoc
    - mv target/site/apidocs public
  artifacts:
    paths:
      - public
  only:
  - master
  - dev_main
