image: maven:latest

stages:
  - build
  - docs
  - format

build:
  stage: build
  script:
    - mvn test
    - mvn compile

format:
  stage: format
  script:
    - mvn spotless:apply

docs:
  stage: docs
  script:
    - mvn javadoc:javadoc
    - mvn site
    - mv target/site/ public
  artifacts:
    paths:
      - public
