image: maven:latest

stages:
  - build
  - docs
  - check
  - format

build:
  stage: build
  script:
    - mvn test
    - mvn compile

format:
  stage: format
  script:
    - mvn spotless:apply

docs:
  stage: docs
  script:
    - mvn clean site
    - mv target/site/ public
  artifacts:
    paths:
      - public
  only:
  - master
  - dev_main
